# Setup of the CernVM-File system (CVMFS) and configure so that the reference
# data hosted by Galaxy on usegalaxy.org is available to the remote target.
- hosts: localhost
  connection: local
  remote_user: root
  tasks:
    - name: Install CernVM apt key
      apt_key:
        url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg

    # Install & setup CermVM-FS
    - name: Configure CernVM apt repository
      apt_repository:
        filename: "cernvm.list"
        mode: 422
        repo: deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main

    - name: Install CernVM-FS client (apt)
      apt:
        name: ['cvmfs', 'cvmfs-config']
        state: "{{ galaxy_apt_package_state }}"
        update_cache: yes

    - name: Make CernVM-FS key directories
      file:
        state: directory
        path: "{{ item }}"
        owner: "root"
        group: "root"
        mode: "0755"
      loop: "{{ cvmfs_keys | map(attribute='path') | map('dirname') | unique }}"

    - name: Install CernVM-FS keys
      copy:
        content: "{{ item.key }}"
        dest: "{{ item.path }}"
        owner: "root"
        group: "root"
        mode: "0444"
      with_items: "{{ cvmfs_keys }}"

    - name: Perform AutoFS and FUSE configuration for CernVM-FS
      command: cvmfs_config setup

    - name: Configure CernVM-FS config repository
      block:

        - name: Create config repo config
          copy:
            content: |
              CVMFS_SERVER_URL="{{ cvmfs_config_repo.urls | join(';') }}"
              CVMFS_PUBLIC_KEY="{{ cvmfs_config_repo.key.path }}"
            dest: "/etc/cvmfs/config.d/{{ cvmfs_config_repo.repository.repository }}.conf"
            owner: "root"
            group: "root"
            mode: "0444"

        - name: Set config repo defaults
          copy:
            content: |
              CVMFS_CONFIG_REPOSITORY="{{ cvmfs_config_repo.repository.repository }}"
              CVMFS_DEFAULT_DOMAIN="{{ cvmfs_config_repo.domain }}"
              CVMFS_USE_GEOAPI="{{ cvmfs_config_repo.use_geoapi | default('yes') }}"
            dest: "/etc/cvmfs/default.d/80-galaxyproject-cvmfs.conf"
            owner: "root"
            group: "root"
            mode: "0444"

    - name: Configure CernVM-FS global client settings
      copy:
        content: |
          CVMFS_HTTP_PROXY="{{ cvmfs_http_proxies | default(['DIRECT']) | join(';') }}"
          CVMFS_QUOTA_LIMIT="{{ cvmfs_quota_limit | default('4000') }}"
          CVMFS_CACHE_BASE="{{ cvmfs_cache_base | default('/var/lib/cvmfs') }}"
          CVMFS_USE_GEOAPI="{{ cvmfs_use_geoapi | default('yes') }}"
        dest: "/etc/cvmfs/default.local"
        owner: "root"
        group: "root"
        mode: "0644"
