- hosts: localhost
  connection: local
  remote_user: root
  vars:
    rabbitmq_version: 4.0.4
    rabbitmq_apt_repository: "deb [signed-by=/etc/apt/trusted.gpg.d/rabbitmq-9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    rabbitmq_apt_gpg_url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
    erlang_apt_repository: "deb [signed-by=/etc/apt/trusted.gpg.d/erlang-E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    erlang_apt_gpg_url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
  roles:
    - role: geerlingguy.rabbitmq
  tasks:
    - name: Enable rabbitmq management plugin
      rabbitmq_plugin:
        name: rabbitmq_management
        broker_state: offline
        state: enabled

    - name: Copy startup script for rabbitmq
      template: src=rabbitmq.sh.j2 dest=/usr/local/bin/rabbitmq.sh

    - name: Install rabbitmq users configuration script
      template: src=configure_rabbitmq_users.yml.j2 dest=/usr/local/bin/configure_rabbitmq_users.yml
    
    - name: Purge systemd and perform cleanup
      shell: apt purge -y systemd && apt-get autoremove -y && apt-get clean
