- hosts: localhost
  connection: local
  roles:
      - role: galaxyprojectdotorg.galaxyextras
        tags: galaxyextras

      - { role: galaxy-letsencrypt-playbook, when: "{{ galaxy_use_https }}" }
