---

- hosts: localhost

  vars:
    # country: "e.g. US" -- define this at runtime with --extra-vars country=___
    # state: "e.g. New York" -- define this at runtime with --extra-vars state=___
    # locality: "e.g. New York" -- define this at runtime with --extra-vars locality=___
    # organization: "e.g. New York University" -- define this at runtime with --extra-vars organization=___
    # common_name: "e.g. galaxy.nyu.edu" -- define this at runtime with --extra-vars common_name=___
    letsencrypt_csr_fields: "/C={{country}}/ST={{state}}/L={{locality}}/O={{organization}}/CN={{common_name}}"

  tasks:
    - assert:
        that:
          - country is defined
          - state is defined
          - locality is defined
          - organization is defined
          - common_name is defined

    - apt: name=openssl update_cache=yes

    - name: Generate RSA key
      command: openssl genrsa -out /etc/pki/cert/private/account.key 2048
        creates: /etc/pki/cert/private/account.key

    - name: Generate CSR
      command: openssl req -new -sha256 -subj "{{ letsencrypt_csr_fields }}" -key /etc/pki/cert/private/account.key -out /etc/pki/cert/csr/sample.com.csr
        creates: /etc/pki/cert/csr/sample.com.csr


    - letsencrypt:
        account_key: /etc/pki/cert/private/account.key
        csr: /etc/pki/cert/csr/sample.com.csr
        dest: /etc/httpd/ssl/sample.com.crt
      register: sample_com_challenge

    - debug: msg="csr submitted, sample challenge registered"
      when: sample_com_challenge|changed

    - copy:
        dest: /var/www/html/{{ sample_com_challenge['challenge_data']['sample.com']['http-01']['resource'] }}
        content: "{{ sample_com_challenge['challenge_data']['sample.com']['http-01']['resource_value'] }}"
      when: sample_com_challenge|changed

    - letsencrypt:
        account_key: /etc/pki/cert/private/account.key
        csr: /etc/pki/cert/csr/sample.com.csr
        dest: /etc/httpd/ssl/sample.com.crt
        data: "{{ sample_com_challenge }}"
      when: sample_com_challenge|changed
