name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install python dependencies
        run: pip install -r docs/src/requirements.txt

      - name: Generate documentation
        run: python docs/src/generate_docs.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
